### ISSUE TITLE
iOS 7 support

### ISSUE THREAD

**Issue by getaaron** [kirpichenko/EKKeyboardAvoiding#2]
On iOS 7, the keyboard animation is bad, and the insets are lost.
### Animations
- The scroll view does not animate until the keyboard is finished animating
- The scroll view animation is jerky - it looks like it's completing two separate animations
### Lost insets
- After dismissing the keyboard, the insets (which had been set using the iOS 7 top layout guide) are reset incorrectly, so the scroll view now scrolls all the way up under the UINavigationBar

**Comment by K-Be** [comment]
It is fixed in the last library version.
